// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FwButton: typeof import('@funkwhale/vui')['FwButton']
    FwInput: typeof import('@funkwhale/vui')['FwInput']
    FwPopover: typeof import('@funkwhale/vui')['FwPopover']
    FwTab: typeof import('@funkwhale/vui')['FwTab']
    FwTabs: typeof import('@funkwhale/vui')['FwTabs']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Line: typeof import('./components/tools/Line.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolLine: typeof import('./components/tools/ToolLine.vue')['default']
  }
}
